import { useWallet } from '@solana/wallet-adapter-react';
import Head from 'next/head'
import Image from 'next/image'
import LoginBox from '../components/LoginBox';
import MainView from '../components/MainView';
import styles from '../styles/Home.module.css'

export default function Home() {
  const { connected } = useWallet()
  let viewToDisplay = connected ? <MainView /> : <LoginBox />;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {viewToDisplay}
    </div>
  )
}
